### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by ArmorDarks** [vitkarpov/grunt-nunjucks-2-html#13]
Not crucial feature, but potentially Task should support i18n. At least, we'd be glad to i18n some of our projects based on that Task.

In current state, we have few options:

1. Use target for defining locales, like so:

  ``` coffee
  module.exports = ->
    @config 'nunjucks',
      enUS:
        options:
          paths: '<%= path.source.layouts %>/'
          data: '<%= data %>'
        files: [
          expand: true
          cwd: '<%= path.source.layouts %>/'
          src: ['{,**/}*.nj', '{,**/}*.html', '!{,**/}_*.nj']
          dest: '<%= path.build.root %>/en-us/'
          ext: '.html'
        ]
      de:
        options:
          paths: '<%= path.source.layouts %>/'
          data: '<%= data %>'
        files: [
          expand: true
          cwd: '<%= path.source.layouts %>/'
          src: ['{,**/}*.nj', '{,**/}*.html', '!{,**/}_*.nj']
          dest: '<%= path.build.root %>/de/'
          ext: '.html'
        ]
  ```

  Potential problems: a lot of code repetitions, since we have to define new targets.

  Besides, there are some avoidable, but nasty issues with passing name of the current locale to the templates as variables and so on...

2. Use additional option, which will be by default `false`, but could accept array of locales:

  ``` coffee
  module.exports = ->
    @config 'nunjucks',
      build:
        options:
          locales: [
            'en-US'
            'de'
          ]
          paths: '<%= path.source.layouts %>/'
          data: '<%= data %>'
        files: [
          expand: true
          cwd: '<%= path.source.layouts %>/'
          src: ['{,**/}*.nj', '{,**/}*.html', '!{,**/}_*.nj']
          dest: '<%= path.build.root %>/en-us/'
          ext: '.html'
        ]
  ```

  Each entry of `options.locales` will

  1. Define into which subfolders should be generated pages
  2. Inject global nunjucks variable, let's say, `locale` or `currentLocale` with name of current locale in loop, so it will be possible to use it in `<html lang='{{ locale }}'>`, hrefs and so on

  Another side benefit is that users would be able to pass here  micro-template like `<%= locales %>`, which could be shared with other i18n-related tasks, like https://github.com/mozilla/grunt-i18n-abide

It's also would be great, if Task would have ability to optionally define base language, for which Task will put generated pages in root of `dest` directory , instead of `dest/<%= localeName %>` subfolder.

Whole idea is quite raw. Maybe you have some better thought regarding it.

**Comment by vitkarpov** [comment]
I've got the point, but I have a question.

How do you define languages in your input data? I mean, you have something line this:

```
'ru': {
  'foo': 'bar'
},
'en': {
  'foo': 'baz'
}
```

?

**Comment by ArmorDarks** [comment]
I'm not sure that current Task should handle parsing and injecting of translation file itself.

The reason is quite simple — l10n files can have different formats and use various features. I always had feeling that it's more translator's duty to write global function or filter which will handle l10n files injection, replacement, inline replacements and so on. Already existing `options.processData` and newly added `options.nunjucksConfigure` seems like perfect fit for that task, but they don't have enough room for implementing of proper structure generation itself.

From other sides, it would be really nice to have already built-in tools for complete i18n, without need to write your own filters and functions, parsing files etc.

Regarding file formats, so far as I know there are few most common file formats used in i18n:

1. Keys-based (json, yaml) — those are based exactly on keys.

  Example of defining in template:

  ``` twig
  Localized value: {{ _t('stringKey') }}
  ```

  They can be:

  1. Exactly same as mentioned by you — series of locales in single file with key-values pairs inside for each string
  2. Splitted into locales (each translation for each locale in separate file, like `en-US.json`, `de.json` and so on)
  3. Splitted into components (usually those also splitted by locales), like `/en-US/sidebar.json`, `/de/sidebar.json` and so on

  Not to mention that structure, names can vary from developer to developer — there is really no strict strucutre for such type of l10n files.

2. Strings-based (gettext) — those using strings itself as identifiers.

  Example of defining in template:
 
  ``` twig
   {# l10n: Comment which some gettext utilities pulling into l10n file for translators #}
  Localized value: {{ _t('my value goes here') }}
  ```

  On contrary to keys-based formats, gettext was developed by GNU and has very strict format, strict structure and good documentation. It considered so far as one of de facto standards for i18n.

  Situation with gettext is a bit more complicated than with keys-based format, since nor node, nor Grunt, as far as I know, don't have build-in tools for parsing and reading it.

  Since gettext can also have plurals (which are very important in l18n process), handling of this format (even if it would be parsed) and proper output can be tricky, though possible.

  More over, when you're l10n, let's say, js-application, it's usually very important to have ability to use inline expressions in translation. Gettext supports it too, but it adds one more challenge for implementation during output of generated pages.

  [grunt-i18n-abide](https://github.com/mozilla/grunt-i18n-abide), for example, workarounding that issue by introducing `abideCompile` task, which converts gettext file into easily readable single json file. However, unfortunately, it doesn't support plurals, and I'm not sure that it can handle inline expressions properly.

3. XLIFF — uses xml. It was popular in past and some systems still prefer it over other formats. Has a lot of good features, but... xml... just no. That's all :)

4. Some other less popular formats, like Mozilla's [l20n](http://l20n.org/) or unkown to me

So, I mean that covering all needs may be really hard.

I've managed translations for more then a year and I must say that so far gettext is best what we have. It isn't perfect, there are some things that I'd prefer to do in completely another way, and it's syntax in compare with beauty and simplicity of yaml isn't best thing... but at least it isn't xliff, while it's features still quite good.

So, if someone would ask me which format current Task should support — I'd say gettext. However, since it would be much harder to implement, I think that for basic implementation we have to go with simpler key-based format.

It's just important to introduce room for those, who would prefer to implement using of gettext format by it's own.

**Comment by ArmorDarks** [comment]
For some reason I've completely missed other big i18n issue — pathways and filenames remapping.

The thing is, that nowadays it's better to use l10ed urls — for example. for `ru` — cyrillic urls, for `de` — translated into German urls and so on.

Unfortunately, in case of i18n handling of l10ed urls becomes quite nontrivial, since require some way to define and remap final urls and files baseNames itself, not just new subdoman or `/de/` subfolder.

To be honest, so far I don't have even approximate vision how remaping can be done flexible and fitable for all possible workflows (for example, different developers may prefer to store info about urls l10n in different files, or in database, etc.)

**Comment by vitkarpov** [comment]
To tell the truth, I don't think that adding i18n-support right inside the plugin is a good idea.

You can avoid of a lot code's repetitions you've mentioned (such you have to support several tasks) by generating them automatically using some custom helper function, delated somewhere inside gruntfile.

Now I can't understand how to make a right support.

By the way, thank you for details about common i18n issues.

**Comment by ArmorDarks** [comment]
> To tell the truth, I don't think that adding i18n's support right inside the plugin is a good idea.

That's what about was my first lines :) In fact, all explanation of differences between l10n files was written to show that completely built-in solution, suitable for all, merely impossible. Unless it will be very specific, of course.

The things is, we shouldn't care much about how devs will process l10n data, how it should look like, how he will use received values and input them into templates — he can take care of it with help of `options.configureNunjucks` and `options.processData`.

We just have to added tools to influence things, which are out of `options.configureNunjucks` and `options.processData` scope, can't be done with their help. Since, well, forking Task and monkeypatching it never seemed to me like right thing to do...

If you're interested, I may write down list of needed additions (from my point of few), without which complete i18n becomes quite tricky.

> Now I can't understand how to make a right support.

I really hoped that maybe you had experience with i18n before, since while I'm coordinated translation for quite a while, I never had to i18n any apps before, especially, in, well, right way — without using tricks ans hacks.

Anyhow, if you will have time and willing for reading my long and boring posts about how it should probably be implemented — I'll try to do my best.

**Comment by vitkarpov** [comment]
Usually `i18n` is a special theme, out of responsibilities of template engine.

For instance, there's a special `i18n` function which you could use into your templates. There's another task which should create some different templates — one for each locale, and `i18n` function will be replaced with its localized values.

Then nunjucks compiles each template into corresponding html.

**Comment by vitkarpov** [comment]
Do you familiar with a such way?

**Comment by vitkarpov** [comment]
Seems there's no life here anymore. We always can continue the discussion via email. Thank you.

**Comment by ArmorDarks** [comment]
Sorry for abandoning issue about i18n of grunt task.

I wanted to test out things in real environment, understand better needs of i18n, what can and what can't be done without changing anything in current task before making any judgements.

Unfortunately, I had to dedicate my attention to other ongoing projects, thus I never had time to pay as much as I wanted attention to this issue.

Recently I've finally got time to work with i18n closer, test out different libs and ways.

So, I've ended up writing kind of wrapper for task. For now, it works just as pre-builder of task and it's locale-based targets before `grunt-nunjucks-2-html` invocation.

I thought that maybe you would have time and willing to take a look at it. In the end of all, you have much more experience with JS and Grunt. Maybe you will propose some better ways to solve that issue, or even would like to integrate some parts of it into core task.

Alternatively, I was thinking about making it standalone task, which would serve as wrapper for grunt-nunjucks-2-html.

Most important part of code is dynamic building of targets for each locale and passing i18n-related variables to nunjucks global scope (`locales`, `page.locale`, etc.). For now, I think it's the only way how building for each locale can be handled — via loop. Though, if it would become part of task's core, there would be no need to build custom targets per each locale, I think.

All other stuff is pretty opinionated, I'd say it shouldn't be part of core. Or should provide very flexible ways of configuration.

Provided task configuration will build each locale into `/*locale-name*/` directory, except base locale (which is usually English). Base locale will be built into specified cwd directory.

So, here we go:

``` coffee
###
Nunjucks to HTML
https://github.com/vitkarpov/grunt-nunjucks-2-html
Render nunjucks templates
###
module.exports = (grunt) ->

  # Configuration
  locales    = ['en-US', 'ru', 'zh-CN']
  baseLocale = 'en-US'
  localeSrc  = grunt.template.process('<%= path.source.locales %>')



  # Globals and requires
  path       = require('path')
  Gettext    = require('node-gettext')
  i18n       = new Gettext()
  sprintf    = require('sprintf-js').sprintf
  vsprintf   = require('sprintf-js').vsprintf # @note Not used so far

  layoutsDir = grunt.template.process('<%= path.source.layouts %>')



  # Helpers

  # Output or not locale name based on whether it's base locale or not.
  resolveLocaleDir = (loc) ->
    if loc == baseLocale then '' else loc



  # Load and invoke content of l10n files
  # @note Though that part of code will load all `.po` files, contained in locale's directory,
  #       including subdirectories, due to limitation of `node-gettext` for now only last loaded
  #       file will be actually used
  locales.forEach (locale) ->

    grunt.file.expand({ cwd: localeSrc + '/' + locale, filter: 'isFile' }, '**/*.po').forEach (file) ->

      messages = grunt.file.read(localeSrc + '/' + locale + '/' + file, { encoding: null })
      i18n.addTextdomain(locale, messages)



  # Build task body
  Task = ->

    self = @

    # Define targets, with unique options and files, for each locale
    locales.forEach (locale, index, array) ->

      localeDir    = resolveLocaleDir(locale)


      self[locale]         = {}
      self[locale].options = {
        paths: '<%= path.source.layouts %>/'
        data:  '<%= data %>'
        configureEnvironment: (env) ->

          # Append url with locale name based on whether it's base locale or not
          env.addFilter 'resolveUrl', (url, loc) ->
            loc = loc || locale
            return (if resolveLocaleDir(loc) then '/' + resolveLocaleDir(loc) else '') + url

          # Output or not locale name based on whether it's base locale or not.
          env.addFilter 'resolveLocaleDir', (loc) ->
            if resolveLocaleDir(loc) then '/' + resolveLocaleDir(loc) else ''

          # Load string from current locale
          # @note So far `sprintf` support only named placeholders
          env.addGlobal '_t', (string, ph) ->
            ph  = ph || {}
            sprintf(i18n.dgettext(locale, string), ph)

          # Load string from specified locale
          # @note So far `sprintf` support only named placeholders
          env.addGlobal '_dt', (loc, string, ph) ->
            loc = loc || locale
            ph  = ph || {}
            sprintf(i18n.dgettext(loc, string), ph)

          ### ...
          ### There are other gettext functions (like plurals, context etc), but they will be added later
          ### ...

        preprocessData: (data) ->

            fullFilepath = path.dirname(@src[0])

            if fullFilepath == layoutsDir
              filepath = ''
              dirname  = ''
            else
              filepath = fullFilepath.replace(layoutsDir + '/', '')
              dirname  = fullFilepath.split('/').slice(-1)[0]

            data.locales         = locales
            data.baseLocale      = baseLocale

            data.page            = data.page || {}
            data.page.locale     = locale
            data.page.url        = '/' + filepath
            data.page.breadcrumb = filepath.split('/')
            data.page.basename   = path.basename(@src[0], '.nj')
            data.page.dirname    = dirname

            data

      }


      self[locale].files = [
          expand: true
          cwd: '<%= path.source.layouts %>/'
          src: ['{,**/}*.nj', '{,**/}*.html', '!{,**/}_*.nj']
          dest: '<%= path.build.root %>/' + localeDir
          ext: '.html'
        ]



  @config 'nunjucks', new Task()
```

Example usage:

``` twig
<p>{{ _t('Some string') }}</p>

<p>Output specific locale: {{ _dt('zh-CN', 'Some string') }}</p>

<p>With placeholders:: {{ _t('Some %(type)s string', { type: Funky }) }}</p>
```
It needs to be installed via npm `node-gettext` and `sprintf-js`.

If you're interested to try it out, I can make testing repository with configurated tasks. We're planing to make it part of [Kotsu](https://github.com/LotusTM/Kotsu), but so far I'm unsure — should it remain like that, or should it be converted into wrapping task for grunt-nunjucksl-2-html, or maybe you would like to incorporate it's common for all i18n approaches parts into core.

I would really appreciate any critique and proposals.

> Usually i18n is a special theme, out of responsibilities of template engine.

> For instance, there's a special i18n function which you could use into your templates. There's another task which should create some different templates — one for each locale, and i18n function will be replaced with its localized values.

> Then nunjucks compiles each template into corresponding html.

Well, that's completely true, but, to be honest, never worked for me. Most critical issue is i18n variables and functions, without which Nunjucks won't be able to fully build static i18ned site. Since current task is the only way to pass vars, functions and filters to Nunjucks, i18n can't be handled by completely separate task, except if it's wrapper of grunt-nunjucks-2-html.

Alternatively it's possible to use client-side translation, but in our case we'd prefer pre-built, static translation.

**Comment by ArmorDarks** [comment]
I guess you don't have much time to look into that code :)

So, maybe I should convert it in standalone Grunt task, which will use `grunt-nunjucks-2-html` as wrapper?

**Comment by vitkarpov** [comment]
Yep, I think it's the right way. At least for a while. Thanks.

**Comment by ArmorDarks** [comment]
Just for the information, mentioned above script has been refactored and embedded into Kotsu.

So, from now Kots supports full i18n of generated static sites based on gettext: https://github.com/LotusTM/Kotsu

Index page has few examples for curios ones.

We hope to find some time in future for rewriting of Kotsu [wrapper](https://github.com/LotusTM/Kotsu/blob/master/tasks/grunt-nunjucks-2-html.coffee) around `grunt-nunjucks-2-html` into standalone Grunt task, but for now it will exist as it is.
