### ISSUE TITLE
Undefined err

### ISSUE THREAD

**Issue by ArmorDarks** [vitkarpov/grunt-nunjucks-2-html#18]
I'm not sure, but it's looks like that `err` variable is undefined by the time script reaches that line:

https://github.com/vitkarpov/grunt-nunjucks-2-html/blob/master/tasks/nunjucks.js#L49

Whenever there is an error in templates, Grunt throughs that message:

```
File "tests/_output.html" created.
>> Template render error: (unknown path)
>>   Error: template not found: /import/base.html
Warning: err is not defined Use --force to continue.
```

**Comment by vitkarpov** [comment]
Done https://github.com/vitkarpov/grunt-nunjucks-2-html/commit/2c0969e8be459f719cec5336de9a370a60a6efeb

**Comment by ArmorDarks** [comment]
thanks!
