### ISSUE TITLE
Undefined path in errors

### ISSUE THREAD

**Issue by ArmorDarks** [vitkarpov/grunt-nunjucks-2-html#25]
Hi

There is issue with errors from Nunjucks tasks — they always shows `unknown path`:

![2015-09-19_12-24-52](https://cloud.githubusercontent.com/assets/4460311/9975590/80594982-5ec9-11e5-80c0-4cdd6524e9ee.png)

Seems that error expects `path` as one of arguments, but it never receives it. Here is part of code from Nunjucks itself:

![he0qdff](https://cloud.githubusercontent.com/assets/4460311/9975597/e89040b4-5ec9-11e5-94c3-4ec21d1d6085.png)

**Comment by vitkarpov** [comment]
Hey, how's it going? Which nunjucks' version do you use?  I have just downloaded nunjucks 2.0.0 and `npm test` says okay.

**Comment by vitkarpov** [comment]
![](https://yadi.sk/i/abpuBH9PjCreU_XXL.jpg)

**Comment by vitkarpov** [comment]
Oh, now I see the error — the test is not okay

**Comment by vitkarpov** [comment]
@ArmorDarks check out `0.3.1` version of the plugin. Does it work fine for you now?

**Comment by ArmorDarks** [comment]
Thanks

Unfortunately, issue still there:

![1psbmhi](https://cloud.githubusercontent.com/assets/4460311/9982677/b2d81bee-5fec-11e5-9654-ee8bb7e701d0.png)


btw, am I wrong, or it's actually throwing an warning, while should throw an error?

**Comment by vitkarpov** [comment]
It seems similar to https://github.com/mozilla/nunjucks/issues/352 — trying to use `env.render` instead of `renderString`

**Comment by vitkarpov** [comment]
https://github.com/vitkarpov/grunt-nunjucks-2-html/pull/27

**Comment by vitkarpov** [comment]
@ArmorDarks try to use `v0.3.2`

**Comment by ArmorDarks** [comment]
Wow, it works! 

![2015-09-21_09-25-32](https://cloud.githubusercontent.com/assets/4460311/9986234/caca4b4a-6042-11e5-9677-66e23ba96d8e.png)

I'd never thought that issue lays in rendering method... I guess `renderString` should pass proper path in errors too. Would you have time to open issue in Nunjucks repository, or should I?

**Comment by ArmorDarks** [comment]
Unfortunately, seems that `render` and then `grunt.write.file` seems to be 1.5 times slower:

With `renderString` method:

![1](https://cloud.githubusercontent.com/assets/4460311/9986336/1b5d1f46-6044-11e5-9316-55a26aef1850.png)

With `render` method:

![2](https://cloud.githubusercontent.com/assets/4460311/9986337/1e98433e-6044-11e5-81c4-1bb68347285e.png)

(around 70 templates)

So, in case issue could be fixed in Nunjucks, it would be better to return to `renderString` method

**Comment by vitkarpov** [comment]
Yep. I think we can try to get back `renderString` method and get rid of warnings at the same time

**Comment by vitkarpov** [comment]
Check out v0.3.3

**Comment by vitkarpov** [comment]
Undefined paths were 'cause of `renderString` method isn't sync anymore (nunjucks 2.0.0 has changed api)

**Comment by ArmorDarks** [comment]
With v0.3.3 `unknown path` returned

**Comment by ArmorDarks** [comment]
Also note, that from now due to latest changes in async behavior task fails on quite wrong place:

![3](https://cloud.githubusercontent.com/assets/4460311/9987038/ea17695c-604b-11e5-9522-45833fd757c5.png)

Instead of `Fatal error`, it should exit with `grunt.warn('Something went wrong.')` I think, since it's not critical error and user should have ability to use `--force` to skip it when needed

**Comment by vitkarpov** [comment]
Okay, let's define the problems:

- you wanna see the message of the error and other templates should be processed independent
- unknown path is a strange nunjucks' issue which can be reproduced with `renderString` method but with `render` (v0.3.2) is okay?

**Comment by vitkarpov** [comment]
And am I right in assuming that you need to fix the error anyway (questionBlock is undefined)?

**Comment by ArmorDarks** [comment]
> you wanna see the message of the error and other templates should be processed independent?

not exactly. Let's drop that part, since it's out of scope of current issue (my bad). I will create new issue with more detailed explanation of what seems wrong to me about it.

> unknown path is a strange nunjucks' issue which can be reproduced with renderString method but with render (v0.3.2) is okay?

yes. I assume this means that it's upstream issue. If you don't have time for it, I will create Issue in Nunjucks repository. Right?

> And am I right in assuming that you need to fix the error anyway (questionBlock is undefined)?

nope :) it's just liberately introduced mistake — call of non existing macro — to test out current error's behaviour.

Solely purpose of that issue is to understand, why errors produces messages with `unknown path` instead of real paths.

**Comment by vitkarpov** [comment]
Okay. To get rid of `undefined` paths we need to use `render` instead of `renderString` and make an issue for `nunjucks`.

Can you create a related issue?

**Comment by ArmorDarks** [comment]
> Okay. To get rid of undefined paths we need to use render instead of renderString and make an issue for nunjucks.

I think it's better to stick with `renderString`, despite that issue with `undefined` paths. In the end of all, it works faster, while paths not so crucial

> Can you create a related issue?

Done: https://github.com/mozilla/nunjucks/issues/529

**Comment by ArmorDarks** [comment]
Hm, quite strange...

I've made some more tests (around 70 templates on real project)

With v0.3.0:

![30](https://cloud.githubusercontent.com/assets/4460311/10020699/02f2bac4-614d-11e5-9b9e-faa130bd7094.png)

With v0.3.1:

![31](https://cloud.githubusercontent.com/assets/4460311/10020704/07e17fc0-614d-11e5-8103-88883280c5e8.png)

I've wrongly concluded that `render` method is slower than` renderString`, but actually it isn't — it's performance exactly same (maybe a bit slower, but my tests isn't that accurate)

So, we can freely switch to `render` method which doesn't have performance hit and has right error messages.

What is really causing slowness is `_.cloneDeep` method — it has very significant performance hit on large projects.

The question is — does we really need it?

I see that `Object.create` doesn't clone object, but it seems that references aren't affected by other templates — so, maybe we're ok to stick with much faster `Object.create`?

**Comment by vitkarpov** [comment]
@ArmorDarks check out v0.3.4 to clarify the performance issue. I got rid of `_.cloneDeep` so it has to be faster.

If it's sluggish anyway then we should make a new issue for it and make performance tests first of all.

**Comment by vitkarpov** [comment]
I've red your message for commit about performance issue. Close this.

**Comment by ArmorDarks** [comment]
Thanks once again :+1:
