### ISSUE TITLE
Replace jscs with standard

### ISSUE THREAD

**Issue by mrhyde** [vitkarpov/grunt-nunjucks-2-html#35]
This is more as suggestion, since [standard](https://github.com/feross/standard) has some pretty radical rules (like omitting semicolons), but it has a lot of advantages and more and more projects adopting it (even [npm](https://github.com/npm/npm) itself)

What do you think?

**Comment by mrhyde** [comment]
Small clarification of benefits:
0. Zero configuration. It just works
1. No need to think about best practices and most adopted conventions - it's already there
2. No need of maintaining and updating rules
3. It's even comes with automatic formatter

**Comment by vitkarpov** [comment]
I think it's a great idea. Wanna make a pr?

**Comment by mrhyde** [comment]
Sure. I'll do it once I get home :)

**Comment by mrhyde** [comment]
see https://github.com/vitkarpov/grunt-nunjucks-2-html/pull/36

**Comment by vitkarpov** [comment]
Done
