### ISSUE TITLE
 SyntaxError (...) Use of const in strict mode.

### ISSUE THREAD

**Issue by anthonygrignoux** [vitkarpov/grunt-nunjucks-2-html#38]
I feel a little dumb for opening an issue for my particular problem, I might just not be good enough to understand what's wrong.

But when I launch the nunjucks task I end up with the following error:

Loading "nunjucks.js" tasks...ERROR
SyntaxError: D:\Works\www\my-project\node_modules\grunt-nunjucks-2-html\tasks\nunjucks.js:11
const nunjucks = require('nunjucks')
Use of const in strict mode.

I understand it has to do with the ES6 syntax not being recognized.

Am I missing a dependency to make it work?

**Comment by vitkarpov** [comment]
Which version of node do you use?

```
$> node --version
```

**Comment by anthonygrignoux** [comment]
v0.12.7

**Comment by anthonygrignoux** [comment]
Wow I didn't realize I was using such an old version, that must be the problem

**Comment by vitkarpov** [comment]
Since 1.0.0 we moved to es6 and nodejs 4.x. You need to update nodejs or use an old grunt-nunjucks-2-html version

**Comment by anthonygrignoux** [comment]
Thx for the help, it was indeed a dumb problem.

**Comment by vitkarpov** [comment]
it's ok. Drop me a line if there's something.
