### ISSUE TITLE
Nunjucks Environment Filter #question

### ISSUE THREAD

**Issue by webdesignberlin** [vitkarpov/grunt-nunjucks-2-html#39]
Hi,

how can i implement filter to the grunt configuration?
I have try to add the nunjucks-date-filter, but it doesnt work (`Warning: dateFilter is not defined`).

Gruntfile: 
```js
module.exports = function (grunt){
	  var globalConfig       = {};
	  globalConfig.root      = '.';
	  globalConfig.app       = globalConfig.root + '/app';
	  globalConfig.dist      = globalConfig.root + '/dist';
	  
	  require('load-grunt-config')(grunt, {
	        // ...
	        jitGrunt: {
	            jitGrunt: true,
                    staticMappings: {
		        nunjucks: 'grunt-nunjucks-2-html'
		    }
	        },
	    	data: {
		    pkg          : grunt.file.readJSON('package.json'),
		    globalConfig : globalConfig,
		    global       : grunt.file.readJSON(globalConfig.app + '/global.json'),
		    joblist       : grunt.file.readJSON(globalConfig.app + '/joblist.json')
	  	}
    });
};
```

grunt/nunjucks.js
``` js
module.exports = {

  dev: {
    options: {
      paths: '<%=globalConfig.app%>/',
      data: {
        global: '<%=global %>', // import global.json from Gruntfile.js
        joblist: '<%=joblist %>'
      },
      configureEnvironment: function(env) {
        env.addFilter('date', dateFilter);
      }
    },
    files: [
      {
        expand: true,
        cwd: "<%=globalConfig.app%>/",
        src: "**/*.html",
        dest: "dist/",
        ext: ".html"
      }
    ]
  }


};
```

Some ideas?
best regards, micha

**Comment by vitkarpov** [comment]
Hi, Micha!

Where do you define `dateFilter ` inside your `grunt/nunjucks.js` file? Maybe you should to define it in the root gruntfile inside data section and use here like that: `<%=dateFilter%>`?

**Comment by webdesignberlin** [comment]
Hi Viktor,

I have tried the following:
Gruntfile.js
```js
module.exports = function (grunt){
  var dateFilter = require('nunjucks-date-filter');
  require('load-grunt-config')(grunt, {
    jitGrunt: {
      jitGrunt: true,
      staticMappings: {
        nunjucks: 'grunt-nunjucks-2-html'
      }
    },
    data: {
      dateFilter: dateFilter
    }
  });
};
```

grunt/nunjucks.js
```js
options: {
  configureEnvironment: function(env) {
    env.addFilter('date', '<%=dateFilter %>');
  }
}
```
But then i became this error:
```sh
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'nunjucks'
```

**Comment by vitkarpov** [comment]
If you write just `env.addFilter('date', function(date) { return date; })`, is it ok?

**Comment by webdesignberlin** [comment]
Yeah this works, but the Filter doesnt work `{{ date.created_at | date('d.m.Y') }}`. Format for `date.created_at` = '2015-12-20' and output is the sane without reorder.

**Comment by ArmorDarks** [comment]
Hi

You're getting this error, because `grunt/nunjucks.js` file is unaware about content of `Gruntfile.js`, since it's just module. So it can't pickup your `require` from `Gruntfile.js`.

This should work:

``` javascript
// grunt/nunjucks.js

options: {
	configureEnvironment: function(env) {
		var dateFilter = require('nunjucks-date-filter');

		env.addFilter('date', dateFilter);
	}
}
```

**Comment by webdesignberlin** [comment]
Hmmm,
if i use this:
```js
// grunt/nunjucks.js

options: {
    configureEnvironment: function(env) {
        var dateFilter = require('nunjucks-date-filter');

        env.addFilter('date', dateFilter);
    }
}
```

i became a `Warning: Cannot find module 'nunjucks' Use --force to continue.`

Only the return date function does not break off, but filter doesnt work:
```js
configureEnvironment: function(env) {
  var dateFilter = function(date) { return date; };
  env.addFilter('date', dateFilter);
}
```

I'm not sure if it is due to 'grunt-nunjucks-2-html', 'nunjucks-date-filter', 'load-grunt-config' or 'jit-grunt'.

**Comment by webdesignberlin** [comment]
Okay. I've found the problem. The culprit is called "nunjucks-date-filter". If i use nunjucks-date, it works fine.

**Comment by vitkarpov** [comment]
> Only the return date function does not break off, but filter doesnt work

'course it doesn't work — I just wanna check where's the problem. Seems `grunt-nunjucks-2-html` works fine.

Maybe you should require the filter in the root gruntfile

```js
data: {
  dateFilter: require('nunjucks-date-filter')
}
```

and the use it inside `grunt/nunjucks.js` as we already tried:

```js
env.addFilter('date', <%=dateFilter%>);
```

Seems there's a problem with requiring nunjucks inside `nunjucks-date-filter` module. Requiring it inside the root script could solve the issue

**Comment by vitkarpov** [comment]
> If i use nunjucks-date, it works fine.

Oh, great! It works as @ArmorDarks suggested?

**Comment by webdesignberlin** [comment]
No, the Problem is the "nunjucks-date-filter" Plugin. If i use "nunjucks-date" ad Plugin, it works. Your suggestion I had tried, unfortunately without success. So now i use nunjucks-date and already is fine :)
```js
configureEnvironment: function(env) {
        var nunjucksDate = require('nunjucks-date');
        //nunjucksDate.setDefaultFormat('YYYY.mm.dd');
        nunjucksDate.install(env);
      },
```

**Comment by vitkarpov** [comment]
Cool! :+1:
