### ISSUE TITLE
Document Nunjucks environment options

### ISSUE THREAD

**Issue by ArmorDarks** [vitkarpov/grunt-nunjucks-2-html#40]
Trying not to forget to document them :)

**Comment by vitkarpov** [comment]
Do you mean `env` methods like adding a new filter or global variable? I think it's ok to drop a link to nunjucks' docs page

**Comment by ArmorDarks** [comment]
I mean those https://github.com/vitkarpov/grunt-nunjucks-2-html/blob/master/tasks/nunjucks.js#L45

**Comment by vitkarpov** [comment]
Yep, I think that we can drop a link to original doc with options, don't we?

**Comment by ArmorDarks** [comment]
yeap

**Comment by vitkarpov** [comment]
Done
